[project]
name = "llama4-scout-lcw-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.6.0",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
    "transformers[hf-xet]>=4.51.2",
]
